# The URL the site will be built for
base_url = "https://1k6a.com"
# dev

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "simple-dev-blog"
taxonomies = [ { name = "tags" } ]

title = "kyohei's blog"
description = "A personal blog"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
nav = []

site_description = "A personal blog"
profile_small = "profile-pic_thumb.jpg"
icon = "icons/icon-48x48.png"

footer_page = """
© 2024, all rights reserved
"""

footer_about = """
"""

accent="#ff3412"
accent_light="#fba595"

gtag = "G-BX4DXEW9QP"
twitter="kyoheiz"


[extra.author]
name = 'Kyohei Tsukuda'
photo = '/photo.jpg'
bio = 'no bio'
contacts = [
  { name = "email", url="mailto:tsukuda.kyouhei@gmail.com" },
  { name = "facebook", url="https://www.facebook.com/kyoheirt" },
  { name = "X", url="https://x.com/kyoheiz" },
  { name = "GitHub",  url="https://github.com/kyohei8" }
]
